### ISSUE TITLE
Did you released it to public maven repo?

### ISSUE THREAD

**Issue by xiaoshao** [apache/incubator-servicecomb-java-chassis#102]
I could not get java-chassis-dependencies from public maven repo.  But following your official document, It is necessary.

where can I get it?

**Comment by seanyinx** [comment]
it is on maven central repo

https://mvnrepository.com/artifact/io.servicecomb/java-chassis-dependencies

**Comment by xiaoshao** [comment]
Here is the dependencies in my project.
`<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.servicecomb</groupId>
                <artifactId>java-chassis-dependencies</artifactId>
                <version>0.1.0</version>
                <type>pom</type>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        
            
            
            
        
        <dependency>
            <groupId>io.servicecomb</groupId>
            <artifactId>transport-rest-vertx</artifactId>
            <version>0.1.0</version>
        </dependency>
        <dependency>
            <groupId>io.servicecomb</groupId>
            <artifactId>spring-boot-starter-provider</artifactId>
            <version>0.1.0</version>
        </dependency>
        <dependency>
            <groupId>io.servicecomb</groupId>
            <artifactId>provider-springmvc</artifactId>
            <version>0.1.0</version>
        </dependency>
    </dependencies>`

And I startup the project with spring boot as following. 
`package com.mycompany.app;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Hello world!
 *
 */
@SpringBootApplication
public class App 
{
    public static void main( String[] args ) throws Exception {
        SpringApplication.run(App.class, args);
    }
}`

And here is the controller.

`package com.mycompany.app;

import io.servicecomb.provider.rest.common.RestSchema;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

//import javax.ws.rs.core.MediaType;

@RestSchema(schemaId = "SpringMVCHelloWorld")
@RequestMapping(path = "/pojo/rest/hello")
@Controller
public class JaxrsHelloImpl implements Hello {

    @Override
    @RequestMapping(path = "/sayhi/{name}", method = RequestMethod.GET)
    @ResponseBody
    public String sayHi(@PathVariable("name") String name) {
        return "hello " + name;
    }
}
`

The microservice.yml

`APPLICATION_ID: jaxrstest
service_description:
  name: jaxrs
  version: 0.0.1
cse:
  service:
    registry:
      address: http://10.119.42.213:30100
rest:
    address: 0.0.0.0:8080
highway:
    address: 0.0.0.0:7070`

the hello.yml
`swagger: '2.0'
info:
  version: 1.0.0
  title: hello
  x-java-interface: io.servicecomb.samples.jaxrs.Hello
basePath: /pojo/rest/hello
produces:
  - application/json

paths:
  /sayhi:
    post:
      operationId: sayHi
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: correct
          schema:
            type: string
        default:
          description: default
          schema:
            type: string
`

I have an error when startup.

`Exception in thread "main" org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:137)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:536)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:372)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1187)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1176)
	at com.mycompany.app.App.main(App.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.getEmbeddedServletContainerFactory(EmbeddedWebApplicationContext.java:189)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:162)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:134)
	... 13 more
`

**Comment by WillemJiang** [comment]
It looks like the transport-rest-vertx doesn't have EmbeddedWebApplicationContext.
You can take a look at the https://github.com/ServiceComb/ServiceComb-Company-WorkShop example, it shows you how to use spring boot with ServiceComb.

**Comment by lijasonvip** [comment]
@xiaoshao, thanks for your kind attention, this issue will be closed before next Monday if there is no further question about it, because all unsolved issues will be moved to Apache JIRA in next Mondy. Anyway, you can still follow us or open an issue at Apache JIRA https://issues.apache.org/jira/projects/SCB Thanks again!

**Comment by zhengyangyong** [comment]
maven central repo :
https://www.mvnrepository.com/artifact/org.apache.servicecomb/java-chassis-dependencies
