### ISSUE TITLE
按照快速启动教程本地启动后

### ISSUE THREAD

**Issue by lorgine** [apache/incubator-servicecomb-java-chassis#237]
java.net.ConnectException: Failed to connect to /127.0.0.1:9411
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:189) ~[okhttp-3.4.1.jar:na]
	at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:173) ~[okhttp-3.4.1.jar:na]
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114) ~[okhttp-3.4.1.jar:na]
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193) ~[okhttp-3.4.1.jar:na]
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129) ~[okhttp-3.4.1.jar:na]
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98) ~[okhttp-3.4.1.jar:na]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) ~[okhttp-3.4.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.4.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.4.1.jar:na]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109) ~[okhttp-3.4.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.4.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.4.1.jar:na]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.4.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.4.1.jar:na]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124) ~[okhttp-3.4.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) ~[okhttp-3.4.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) ~[okhttp-3.4.1.jar:na]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170) ~[okhttp-3.4.1.jar:na]
	at okhttp3.RealCall.access$100(RealCall.java:33) ~[okhttp-3.4.1.jar:na]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120) ~[okhttp-3.4.1.jar:na]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [okhttp-3.4.1.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]

**Comment by eric-lee-ltk** [comment]
这是由于在IDE中`microservice.yaml`文件中的配置项`servicecomb.tracing.enabled=false`并不生效，要将该配置项移到`application.yaml`中。

**Comment by eric-lee-ltk** [comment]
该问题已在最新的发布版本中修复，@lorgine 如果该问题还出现，则请再次提出；如已修复，则该issue可以close了。

**Comment by lijasonvip** [comment]
@lorgine, thanks for your kind attention, this issue will be closed before next Monday if there is no further question about it, because all unsolved issues will be moved to Apache JIRA in next Mondy. Anyway, you can still follow us or open an issue at Apache JIRA https://issues.apache.org/jira/projects/SCB Thanks again!
