### ISSUE TITLE
不支持java9？

### ISSUE THREAD

**Issue by hank-whu** [apache/incubator-servicecomb-java-chassis#683]
```java
2018-05-02 19:40:36,995 [WARN] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.apache.servicecomb.core.CseApplicationListener#0' defined in URL [jar:file:/C:/Users/mc/.m2/repository/org/apache/servicecomb/java-chassis-core/1.0.0-m1/java-chassis-core-1.0.0-m1.jar!/META-INF/spring/cse.bean.xml]: Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/ws/Holder org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.apache.servicecomb.core.CseApplicationListener#0' defined in URL [jar:file:/C:/Users/mc/.m2/repository/org/apache/servicecomb/java-chassis-core/1.0.0-m1/java-chassis-core-1.0.0-m1.jar!/META-INF/spring/cse.bean.xml]: Initialization of bean failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/ws/Holder
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:563)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:759)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:93)
	at org.apache.servicecomb.foundation.common.utils.BeanUtils.init(BeanUtils.java:37)
	at org.apache.servicecomb.foundation.common.utils.BeanUtils.init(BeanUtils.java:33)
	at benchmark.rpc.Server.main(Server.java:10)
Caused by: java.lang.NoClassDefFoundError: javax/xml/ws/Holder
	at org.apache.servicecomb.serviceregistry.client.http.ServiceRegistryClientImpl.getServiceCenterInfo(ServiceRegistryClientImpl.java:742)
	at org.apache.servicecomb.serviceregistry.registry.AbstractServiceRegistry.init(AbstractServiceRegistry.java:106)
	at org.apache.servicecomb.serviceregistry.registry.RemoteServiceRegistry.init(RemoteServiceRegistry.java:51)
	at org.apache.servicecomb.serviceregistry.RegistryUtils.init(RegistryUtils.java:64)
	at org.apache.servicecomb.core.CseApplicationListener.setApplicationContext(CseApplicationListener.java:81)
	at org.springframework.context.support.ApplicationContextAwareProcessor.invokeAwareInterfaces(ApplicationContextAwareProcessor.java:121)
	at org.springframework.context.support.ApplicationContextAwareProcessor.postProcessBeforeInitialization(ApplicationContextAwareProcessor.java:97)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1581)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554)
	... 13 more
Caused by: java.lang.ClassNotFoundException: javax.xml.ws.Holder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 23 more

```

代码位置：https://github.com/hank-whu/rpc-benchmark/tree/master/servicecomb-server

**Comment by zhengyangyong** [comment]
>Java SE 9 has reached end of support. Users of Java SE 9 should switch to Java SE 10.

We may need upgrade to SE 10?

**Comment by WillemJiang** [comment]
It's missing the jaxws jar in the classpath.  I may fix it by starting  JVM with "--add-modules java.xml.bind" option.  here are [some discussion](https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j) in the stackoverflow.

**Comment by hank-whu** [comment]
搞定
