### ISSUE TITLE
怎样平滑关闭Client？

### ISSUE THREAD

**Issue by hank-whu** [apache/incubator-servicecomb-java-chassis#685]
如题，怎样平滑关闭Client？

**Comment by zhengyangyong** [comment]
Can you give more description for this requirement? Thanks!

**Comment by zhengyangyong** [comment]
I think you can try this step:
```java
//this code will Unregister microservice instance from ServiceCenter
((ConfigurableApplicationContext) BeanUtils.getContext()).close();

//Shutdown jvm
System.exit(0);
```

**Comment by hank-whu** [comment]
不行的，还是有线程没被正确关闭

```java
<JMH had finished, but forked VM did not exit, are there stray running threads? Waiting 9 seconds more...>

Non-finished threads:

Thread[transport-vert.x-eventloop-thread-3,5,main]
  at java.base@9.0.4/sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
  at java.base@9.0.4/sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:296)
  at java.base@9.0.4/sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:278)
  at java.base@9.0.4/sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:159)
  at java.base@9.0.4/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
  at java.base@9.0.4/sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
  at app//io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
  at app//io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:753)
  at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:409)
  at app//io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
  at java.base@9.0.4/java.lang.Thread.run(Thread.java:844)
```

**Comment by zhengyangyong** [comment]
Hi,@hank-whu, we had support gracefully shutdown https://github.com/apache/incubator-servicecomb-java-chassis/pull/693, you can check and close this issue if solved
